NetCoreApp/Pages/Home/index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;

namespace NetCoreApp.Pages.Home
{
    public class indexModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPostSetLanguageAsync(string culture, string returnUrl)
        {
            //Response.Cookies.Append(
            //    CookieRequestCultureProvider.DefaultCookieName,
            //    CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            //    new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            //);

            Response.Cookies.Append(
                       CookieRequestCultureProvider.DefaultCookieName,
                       CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                       new CookieOptions
                       {
                           Expires = DateTimeOffset.UtcNow.AddYears(1),
                           IsEssential = true,  //critical settings to apply new culture
                           Path = "/",
                           HttpOnly = false,
                       }
                );

            return LocalRedirect(returnUrl);
        }
    }
}

NetCoreApp/Pages/Shared/Error.cshtml.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using System.IO;

namespace NetCoreApp.Pages.Shared
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string Referrer { get; set; }
        public bool ShowReferrer => !string.IsNullOrEmpty(Referrer);

        public string ExceptionMessage { get; set; }
        public bool ShowExceptionMessage => !string.IsNullOrEmpty(ExceptionMessage);
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            Referrer = HttpContext.Request.Headers["referer"];

            // Do NOT expose sensitive error information directly to the client.
            #region snippet_ExceptionHandlerPathFeature
            var exceptionHandlerPathFeature =
                HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            if (exceptionHandlerPathFeature?.Error is FileNotFoundException)
            {
                ExceptionMessage = "File error thrown";
            }
            if (exceptionHandlerPathFeature?.Path == "/index")
            {
                ExceptionMessage += " from home page";
            }
            #endregion
        }
    }
}

NetCoreApp/Pages/Shared/StatusCode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NetCoreApp.Core.Interfaces.Logging;

namespace NetCoreApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class StatusCodeModel : PageModel
    {
        private readonly IAppLogger<StatusCodeModel> _logger;

        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string ErrorStatusCode { get; set; }

        public string OriginalURL { get; set; }
        public bool ShowOriginalURL => !string.IsNullOrEmpty(OriginalURL);

        public StatusCodeModel(IAppLogger<StatusCodeModel> logger)
        {
            _logger = logger;
        }
        public void OnGet(string code)
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            ErrorStatusCode = code;

            #region snippet_StatusCodeReExecute
            var statusCodeReExecuteFeature = HttpContext.Features.Get<IStatusCodeReExecuteFeature>();
            if (statusCodeReExecuteFeature != null)
            {
                OriginalURL =
                    statusCodeReExecuteFeature.OriginalPathBase
                    + statusCodeReExecuteFeature.OriginalPath
                    + statusCodeReExecuteFeature.OriginalQueryString;
            }
            #endregion
        }
    }
}

NetCoreApp/Pages/Shared/StatusCode.cshtml
@page
@model NetCoreApp.Pages.StatusCodeModel
@{
    ViewData["Title"] = "Code Erreur @Model.ErrorStatusCode";
}

<h1 class="text-danger">Code Erreur: @Model.ErrorStatusCode</h1>
<h2 class="text-danger">Une erreur s'est produite lors du traitement de votre demande.</h2>

@if (Model.ShowRequestId)
{
    <h3>ID Requête</h3>
    <p>
        <code>@Model.RequestId</code>
    </p>
}

@if (Model.ShowOriginalURL)
{
    <h3>Original URL</h3>
    <p>
        <code>@Model.OriginalURL</code>
    </p>
}

NetCoreApp/Pages/Shared/_BlazorScriptPartial.cshtml
<script src="_framework/blazor.server.js"></script>

NetCoreApp/Pages/Shared/_Layout.cshtml
<!
DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Net Core App Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    @RenderSection("css", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Net Core App Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item @( ViewBag.Current == EnumMenu.Home?"active":"" ) ">
                    <a class="nav-link" asp-page="/Home/Index">@_localizer["Tableau de bord"]</a>
                </li>
                <li class="nav-item @( ViewBag.Current == EnumMenu.Categorie?"active":"" )">
                    <a class="nav-link" asp-page="/Categorie/Index">@_localizer["Catégorie"]</a>
                </li>
                <li class="nav-item @( ViewBag.Current == EnumMenu.Article?"active":"" )">
                    <a class="nav-link" asp-page="/Article/Search">@_localizer["Article"]</a>
                </li>
                <li class="nav-item"><a class="nav-link" asp-page="/Shop/Index">@_localizer["Boutique"]</a></li>
            </ul>
            <partial name="_LoginPartial" />
            <partial name="_SelectLanguagePartial" />
        </div>
    </nav>
    <div class="container" style="padding-top:0px;">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

NetCoreApp/Pages/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<div title="@_localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form class="form-inline my-2 my-lg-0"
          id="selectLanguage"
          asp-page="/Home/Index"
          asp-page-handler="setLanguage"
          asp-route-returnUrl="@Context.Request.Path"
          method="post" role="form">
        @_localizer["Language :  "]
        <select class="form-control mr-sm-2"
                name="culture"
                asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
        <button type="submit" class="btn btn-outline-success my-2 my-sm-0"><i class="fa fa-save"></i></button>

    </form>
</div>

NetCoreApp/Pages/Shared/_bootstrapFileInput.cshtml
    <!-- bootstrap 4.x is supported. You can also use the bootstrap css 3.3.x versions -->
@*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">*@


<!-- if using RTL (Right-To-Left) orientation, load the RTL CSS file after fileinput.css by uncommenting below -->
<!-- link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/css/fileinput-rtl.min.css" media="all" rel="stylesheet" type="text/css" /-->
<!-- the font awesome icon library if using with `fas` theme (or Bootstrap 4.x). Note that default icons used in the plugin are glyphicons that are bundled only with Bootstrap 3.x. -->
@*<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">*@
@*<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>*@
<!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
    wish to resize images before upload. This must be loaded before fileinput.min.js -->
<!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
    This must be loaded before fileinput.min.js -->
<!-- purify.min.js is only needed if you wish to purify HTML content in your preview for
    HTML files. This must be loaded before fileinput.min.js -->
<!-- popper.min.js below is needed if you use bootstrap 4.x (for popover and tooltips). You can also use the bootstrap js
   3.3.x versions without popper.min.js. -->
<!-- bootstrap.min.js below is needed if you wish to zoom and preview file content in a detail modal
    dialog. bootstrap 4.x is supported. You can also use the bootstrap js 3.3.x versions. -->
@*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>*@
<!-- the main fileinput plugin file -->
<!-- following theme script is needed to use the Font Awesome 5.x theme (`fas`) -->
<!-- optionally if you need translation for your language then include the locale file as mentioned below (replace LANG.js with your language locale) -->

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />



@*<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/js/plugins/piexif.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>*@

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/js/plugins/sortable.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/js/plugins/purify.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/js/fileinput.min.js"></script>

@*<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/themes/fas/theme.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.1/js/locales/LANG.js"></script>*@